language: node_js
node_js:
  - stable

sudo: required

notifications:
  email:
    onfailure: change
    onsuccess: change

addons:
  ssh_known_hosts:
    - maxkrasnov.ru

branches:
  only:
  - master

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_b0c2bc9d07da_key -iv $encrypted_b0c2bc9d07da_iv

script:
  - make build

after_success:
  - in deploy.enc -out deploy -d
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa
  - echo 'Run deploy to maxkrasnov.ru server'
  - ssh $TRAVIS_USER@maxkrasnov.ru 'git clone git@github.com:maxkrasnov/ru.maxkrasnov-front.git&&cd ru.maxkrasnov-front&&make deploy'
