language: node_js

node_js:
  - stable

notifications:
  - email: true

addons:
  apt:
    packages:
    - sshpass

branches:
 only:
 - master

services:
  - docker

script:
  - make build
env:
  global:
  - 'TRAVIS_KEY=[TRAVIS_KEY]'

after_success:
  - echo 'Run deploy to maxkrasnov.ru server'
  - touch ~/.ssh/id_rsa.pub
  - echo "${TRAVIS_KEY}" >> ~/.ssh/id_rsa.pub
  - sshpass -p TRAVIS_PASSWORD ssh TRAVIS_USER@maxkrasnov.ru 'git clone git@github.com:maxkrasnov/ru.maxkrasnov-front.git&&cd ru.maxkrasnov-front&&make deploy'
