language: node_js

node_js:
  - stable

notifications:
  - email: true

addons:
  apt:
    packages:
    - sshpass

branches:
 only:
 - master

services:
  - docker

script:
  - make build

after_success:
  - echo 'Run deploy to maxkrasnov.ru server!'
  - echo "${TRAVIS_USER}"
