language: node_js

node_js:
  - stable

notifications:
  email:
    onfailure: change
    onsuccess: change

addons:
  apt:
    packages:
    - sshpass
  sshknownhosts:
    - 95.213.237.4

branches:
 only:
 - master

services:
  - docker

script:
  - make build

after_success:
  - echo 'Run deploy to maxkrasnov.ru server'
  - echo -e "Host maxkrasnov.ru\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sshpass -p '$TRAVIS_PASSWORD' ssh -oStrictHostKeyChecking=no $TRAVIS_USER@95.213.237.4 'git clone git@github.com:maxkrasnov/ru.maxkrasnov-front.git&&cd ru.maxkrasnov-front&&make deploy'
