language: node_js
node_js:
  - stable

notifications:
  email:
    onfailure: change
    onsuccess: change

addons:
  apt:
    packages:
    - openssl
  sshknownhosts:
    - 95.213.237.4

branches:
  only:
  - master

services:
  - docker

before_script:
  - openssl aes-256-cbc -K $encrypted_b0c2bc9d07da_key -iv $encrypted_b0c2bc9d07da_iv
  - in deploy.enc -out deploy -d
  - chmod 600 deploy && mv deploy ~/.ssh/idrsa

script:
  - make build

after_success:
  - echo 'Run deploy to maxkrasnov.ru server'
  - ssh $TRAVIS_USER@95.213.237.4 'git clone git@github.com:maxkrasnov/ru.maxkrasnov-front.git&&cd ru.maxkrasnov-front&&make deploy'
