language: node_js
node_js:
  - stable
sudo: required
notifications:
  email:
    onfailure: change
    onsuccess: change
addons:
  ssh_known_hosts:
    - maxkrasnov.ru
branches:
  only:
  - master
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script:
  - ssh $TRAVIS_USER@maxkrasnov.ru 'rm -rf ru.maxkrasnov-front&&git clone https://github.com/maxkrasnov/ru.maxkrasnov-front.git&&cd
    ru.maxkrasnov-front&&make deploy APP_VERSION=${TRAVIS_TAG}'
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_b0c2bc9d07da_key -iv $encrypted_b0c2bc9d07da_iv
  -in deploy.enc -out deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy
- ssh-add deploy
