language: node_js

sudo: true

node_js:
  - stable

notifications:
  - email: true

addons:
  apt:
    packages:
    - sshpass

branches:
 only:
 - master

services:
  - docker

script:
  - make build

after_success:
  - echo 'Run deploy to maxkrasnov.ru server'
  - sshpass -p '$TRAVIS_PASSWORD' ssh -oStrictHostKeyChecking=no $TRAVIS_USER@95.213.237.4 'git clone git@github.com:maxkrasnov/ru.maxkrasnov-front.git&&cd ru.maxkrasnov-front&&make deploy'
